cmake_minimum_required(VERSION 2.8)

# libfreetype libm
find_library(GLIPHY_LIBRARY NAMES ${CONAN_LIBS_GLIPHY} PATHS ${CONAN_LIB_DIRS_GLIPHY} NO_CMAKE_FIND_ROOT_PATH)

if (DEFINED CONAN_LIBS_FREETYPE)
    find_library(FREETYPE_LIBRARY NAMES ${CONAN_LIBS_FREETYPE} PATHS ${CONAN_LIB_DIRS_FREETYPE} NO_CMAKE_FIND_ROOT_PATH)
    set(GLIPHY_LIBRARY ${GLIPHY_LIBRARY} ${FREETYPE_LIBRARY})
endif(DEFINED CONAN_LIBS_FREETYPE)

if(UNIX AND NOT APPLE)
    set(GLIPHY_LIBRARY ${GLIPHY_LIBRARY} m)
endif(UNIX AND NOT APPLE)

set(GLIPHY_INCLUDE_DIRS ${CONAN_INCLUDE_DIRS})
set(GLIPHY_INCLUDE_DIR ${CONAN_INCLUDE_DIRS_GLIPHY})
set(GLIPHY_LIBRARIES ${CONAN_LIBS})

MESSAGE("** GLIPHY ALREADY FOUND BY CONAN!")
SET(GLIPHY_FOUND TRUE)
MESSAGE("** FOUND GLIPHY:  ${GLIPHY_LIBRARY}")
MESSAGE("** FOUND GLIPHY INCLUDE:  ${GLIPHY_INCLUDE_DIR}")

mark_as_advanced(GLIPHY_LIBRARY GLIPHY_INCLUDE_DIR)

set(GLIPHY_MAJOR_VERSION "1")
set(GLIPHY_MINOR_VERSION "0")
set(GLIPHY_PATCH_VERSION "0")
